name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy index.html to Nginx directory
      run: |
        sudo cp $GITHUB_WORKSPACE/index.html /var/www/html/index.html
        sudo systemctl restart nginx
        pwd
      working-directory: ${{ github.workspace }}
